// <auto-generated />
using System;
using ExitInterviewAgent.Signals.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExitInterviewAgent.Signals.Persistence.Migrations
{
    [DbContext(typeof(SignalsDbContext))]
    [Migration("20261005140241_SignalsSnapshots")]
    partial class SignalsSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("signals")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExitInterviewAgent.Signals.Persistence.EmployerSnapshotRow", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmployerRef")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("View")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SnapshotId", "EmployerRef");

                    b.ToTable("EmployerSnapshots", "signals");
                });

            modelBuilder.Entity("ExitInterviewAgent.Signals.Persistence.SnapshotRow", b =>
                {
                    b.Property<long>("Seq")
                        .HasColumnType("bigint");

                    b.Property<int>("EmployerCount")
                        .HasColumnType("integer");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("IntervalHours")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumGroupSize")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RulesVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Seq");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Snapshots", "signals");
                });
#pragma warning restore 612, 618
        }
    }
}
