// <auto-generated />
using System;
using ExitInterviewAgent.InterviewService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExitInterviewAgent.InterviewService.Persistence.Migrations
{
    [DbContext(typeof(InterviewDbContext))]
    [Migration("20261010204648_AddSessionSettlements")]
    partial class AddSessionSettlements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExitInterviewAgent.InterviewService.Persistence.CreditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateOnly>("CreatedWeek")
                        .HasColumnType("date");

                    b.Property<int>("Delta")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Reference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("StartedHour")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountRef");

                    b.HasIndex("Reason", "Reference")
                        .IsUnique()
                        .HasDatabaseName("IX_CreditEntries_Reason_Reference");

                    b.ToTable("CreditEntries", (string)null);
                });

            modelBuilder.Entity("ExitInterviewAgent.InterviewService.Persistence.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CreatedWeek")
                        .HasColumnType("date");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedWeek");

                    b.HasIndex("Tag")
                        .IsUnique()
                        .HasDatabaseName("IX_SubmissionLedger_Tag");

                    b.ToTable("SubmissionLedger", (string)null);
                });

            modelBuilder.Entity("ExitInterviewAgent.InterviewService.Persistence.PaymentEventRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("AmountMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ReceivedWeek")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ProviderEventId")
                        .IsUnique()
                        .HasDatabaseName("IX_PaymentEvents_ProviderEventId");

                    b.ToTable("PaymentEvents", (string)null);
                });

            modelBuilder.Entity("ExitInterviewAgent.InterviewService.Persistence.ReceiptRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.HasIndex("RecordId");

                    b.ToTable("Receipts", (string)null);
                });

            modelBuilder.Entity("ExitInterviewAgent.InterviewService.Persistence.RecordRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly>("CreatedWeek")
                        .HasColumnType("date");

                    b.Property<string>("EmployerRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Verification")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedWeek");

                    b.HasIndex("EmployerRef");

                    b.ToTable("Records", (string)null);
                });

            modelBuilder.Entity("ExitInterviewAgent.InterviewService.Persistence.SessionSettlementRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly>("SettledWeek")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("IX_SessionSettlements_SessionId");

                    b.ToTable("SessionSettlements", (string)null);
                });

            modelBuilder.Entity("ExitInterviewAgent.InterviewService.Persistence.TicketRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Sub");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("SubmissionTickets", (string)null);
                });

            modelBuilder.Entity("ExitInterviewAgent.InterviewService.Persistence.ReceiptRow", b =>
                {
                    b.HasOne("ExitInterviewAgent.InterviewService.Persistence.RecordRow", null)
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
